---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2
    driver_config:
      box: Win2012R2-dotnet35enabled
      #box_url: http://nexus.lab.brainshark.com/vagrant-boxes/w2k12r2-dotnet35enabled.box
      vm_hostname: w2012R1
      communicator: winrm
      gui: true
    transport:
      name: winrm
      provisoner:
        require_chef_omnibus: 12.4.3

suites:
  - name: default
    run_list:
      - recipe[xm-iis::default]
    attributes:
